-- Drop all tables
DROP TABLE IF EXISTS Book_Has_Author;
DROP TABLE IF EXISTS Author;
DROP TABLE IF EXISTS Book_Has_Genre;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Read_Book;
DROP TABLE IF EXISTS Request;
DROP TABLE IF EXISTS Borrowing_History;
DROP TABLE IF EXISTS Borrow;
DROP TABLE IF EXISTS Activity_Feed_Post;
DROP TABLE IF EXISTS Comment;
DROP TABLE IF EXISTS Review;
DROP TABLE IF EXISTS Bookshelf_Contents;
DROP TABLE IF EXISTS Bookshelf;
DROP TABLE IF EXISTS Book_Club_Membership;
DROP TABLE IF EXISTS Book_Club;
DROP TABLE IF EXISTS Follower;
DROP TABLE IF EXISTS Book;
DROP TABLE IF EXISTS User;

DROP TRIGGER IF EXISTS Add_Activity_Feed_Post;
DROP TRIGGER IF EXISTS Add_Club_Moderator;
DROP TRIGGER IF EXISTS Return_Book;

DROP FUNCTION IF EXISTS num_members;
DROP FUNCTION IF EXISTS book_rating;
DROP FUNCTION IF EXISTS available_copies;
DROP FUNCTION IF EXISTS due_date;

